# fly.toml app configuration file generated for siscompax-api on 2023-06-29T04:52:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "siscompax-api"
primary_region = "qro"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
