export * from './deptos/depto.interface';
export * from './deptos/depto.dto';
export * from './empleado/empleado.interface';
export * from './empleado/empleado.dto';
export * from './empleado/auth.interface';
export * from './empleado/auth.dto';
export * from './empleado/login.dto';
export * from './empleado/auth.input.dto';
export * from './empleado/prueba';
